/// Grammar to parse SQL expressions in for Sql Mapper

// Like SQL strings 'Tim''s dog'
literal = ${  "'" ~ ( "''" | (!"'" ~ ANY) )* ~  "'" }

name = 
self_alias = @{".."}
other_alias = @{"..."}

aux_param = @{"<" ~ name ~ ">"}
name =  @{ ASCII_ALPHA ~ ASCII_ALPHANUMERIC*   }

expr = { (literal | aux_param | other_alias | self_alias ) ~ (literal | aux_param | other_alias | self_alias )*}
query = { SOI ~ expr? ~ EOI }

WHITESPACE = _{ " " }

